AllCops:
    NewCops: enable
    TargetRubyVersion: 2.5

Layout/BlockAlignment:
    Enabled: false

Layout/HashAlignment:
    EnforcedHashRocketStyle: table

Layout/IndentationWidth:
    Width: 4

Layout/LineLength:
    Enabled: false

Naming/FileName:
    Enabled: false

Naming/RescuedExceptionsVariableName:
    PreferredName: exception

Style/FrozenStringLiteralComment:
    Enabled: false

Style/HashSyntax:
    EnforcedStyle: hash_rockets

Style/MultilineBlockChain:
    Enabled: false

Style/RaiseArgs:
    EnforcedStyle: compact

Style/WordArray:
    Enabled: false

